### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by surajsingla333**
Updated endcases validations.
Also, there is a new folder .vscode, in which editor settings are mentioned. Tab = 2 space, different tab spaces were giving errors in validations.

### CODE REVIEW

**Comment by bhaskarSingh** [comment]
> Tab = 2 space, different tab spaces were giving errors in validations.
why is that ?

**Comment by surajsingla333** [comment]
> 
> 
> > Tab = 2 space, different tab spaces were giving errors in validations.
> > why is that ?
> > .vscode, in which editor settings are mentioned. Tab = 2
> > It's prettier config for consistency in the codebase

> > > It was because I didn't check `\t` in the compiler. It is resolved now though. I will remove this .vscode folder in the next commit.

**Comment by bhaskarSingh** [comment]
The way workflow is set is that we never push changes/make pr directly to master branch, develop branch(i.e can be considered as a staging branch where all the changes go which will, later on, get merged to master after proper testing) so please, never make pr directly to master.

**Comment by bhaskarSingh** [comment]
Ask:
Make sure put it to code section for all the chapters are written with empathy for users to follow it

Have empathy for the user and try to complete all the chapters from a user's point of view as if you are going over the chapters for the first time --> i.e run user test --> push changes if any --> then I will review this again & merge the changes @surajsingla333 


Awesome work, the offline compiler is now coming together 🎉

**Pull request merged**
