### PR TITLE
Chapters-view Page - Non-responsive

### PR DESCRIPTION
**Pull request by surajsingla333**
What does this PR do?
Develop the chapters-view page

Description of Task to be completed?
Implementing the design of the chapters-view page, [design](https://www.figma.com/proto/hcoRbRF5fZREDTJkLl7cXk/BUIDL-for-Tezos?node-id=177%3A2&scaling=scale-down-width)
  

How should this be manually tested?
 > check the preview link generated by netlify build 
 > click on start learning button on homepage, you will see the chapters-view page.

### CODE REVIEW

**Comment by bhaskarSingh** [comment]
Would suggest going over [contribution guidelines](https://github.com/buidl-labs/zombies-in-the-room/blob/develop/.github/CONTRIBUTING.md)

**Comment by surajsingla333** [comment]
> 
> 
> Back button should be at the top
> Reduce Image size and font-size for text according to the design
> The horizontal line should be grayish with more hight
> Make it mobile responsive too

The images size are as per the provided desing only.
Will work on other changes

**Comment by bhaskarSingh** [comment]
> The image size is as per the provided design only.

Screenshot 2020-03-31 at 6 42 10 PM

still, the image looks too big, it shifts the focus from chapters list to the image, reducing the image would solve this issue

**Comment by surajsingla333** [comment]
> 
> 
> > The image size is as per the provided design only.
> 
> Screenshot 2020-03-31 at 6 42 10 PM
> 
> still, the image looks too big, it shifts the focus from chapters list to the image, reducing the image would solve this issue

Okay, is it only for the seed image or for the logo as well?

**Comment by bhaskarSingh** [comment]
> rebase continually from develop branch (before beginning work on a feature branch) to avoid/resolve conflicts

I would recommend to deep dive into the [contribution guidelines ](https://github.com/buidl-labs/zombies-in-the-room/blob/develop/.github/CONTRIBUTING.md) more time to get the hang of it.

**Comment by bhaskarSingh** [comment]
> Okay, for the logo as well?

yes

**Comment by surajsingla333** [comment]
Changes are done as per the above comments. Kindly review the PR again.

**Comment by bhaskarSingh** [comment]
> error A page component must export a React component for it to be valid. Please make sure this file exports a React component:

Build is failing

**Pull request closed without merging**
