### PR TITLE
Plant vs Zombie game: Fixes #43

### LINKED ISSUE #43: Play shooting game at end of lesson
**Roadmap for game implementation:**

Using a tabular structure since defined steps need to be followed for the gamification part. For any bugs/ features related specificly to the game please write another comment in this issue itself.

| S.No. | Procedure | Description | Result | ETA | Delivered Time |
| :--- | :--- | :--- | :--- | :--- |  :--- |
| 1. | Research on implementation methods | Study various methods of implementing this game and figure out the best method. | I see two methods that can benefit us: 1. Using DOM directly for making the game (lightweight, easier to implement). 2. Using Canvas (for better support of animations, comparatively difficult). We need to run a pilot to finalize what fits best for us. | 8/04/2020 | 8/04/2020 |
| 2. | Running pilot in a separate repo | First try Method 1 (described above) and stick to it if it fulfills the requirement and move to Method 2 if it doesn't. The outcome is to finalize a Method that suits us best. | Finalized Method 1, pilot deployed [here](http://orange-horn.surge.sh/) | 9/04/2020 9 PM | 9/04/2020 9 PM |
| 3. | Adding sprite animations & correcting the aesthetics | Added sprite animations using steps method in CSS and corrected the aesthetics | Outcome deployed [here](https://orange-horn.surge.sh), feedback awaited | 10/04/2020 9 PM | 10/04/2020 9 PM |
| 4. | Implement onboarding animations and integration with the main repo |  | Integrated with the main repo, the team decided to move characters into separate components so putting the before adding animation | 12/04/2020 9 PM | 13/04/2020 10 PM |
| 5. | Using Plant as a combo of separate components |  |  | 15/04/2020 12 AM | |
| 5. | Onboarding animations |  |  | 15/04/2020 9 PM | |

### PR DESCRIPTION
**Pull request by dhruv10**
Only setup, does not contains anything except a sample layout

### Before you submit, please check that:

- [ ] You labeled the PR with appropriate labels, if any.
- [x] You mentioned a related issue if this PR related to it, e.g. `Fixes #22` or `Related #17`.
- [ ] You performed a self-review of your own code
- [x] You commented on code, particularly in hard-to-understand areas
- [ ] You asked any particular reviewer to review. If you aren't sure, ask.
- [ ] Your PR adheres to our `CONTRIBUTION GUIDELINES`

After you've read this notice feel free to remove it.
✄ -----------------------------------------------------------------------------

**What does this PR do?**
A clear and concise description of what the PR aims to accomplish.

**Description of Task to be completed?**

**How should this be manually tested?**
A clear and concise description of how the changes can be tested.

**Any background context you want to provide?**

**Screenshots(optional)**
If applicable, add screenshots to help to explain the problem/solution.

**Additional context(optional)**
Add any other context if any.

### CODE REVIEW

**Comment by bhaskarSingh** [comment]
I prefer to rebase, it keeps the branch history clean before merging, [Workflow Link](https://github.com/buidl-labs/zombies-in-the-room/wiki/Git-Workflow)
let me know if you need an overview of the workflow or if something is unclear

**Comment by dhruv10** [comment]
> I prefer to rebase, it keeps the branch history clean before merging, [Workflow Link](https://github.com/buidl-labs/zombies-in-the-room/wiki/Git-Workflow)
> let me know if you need an overview of the workflow or if something is unclear

Got it @bhaskarSingh, will use rebase from onwards.

**Comment by bhaskarSingh** [comment]
Screenshot 2020-04-20 at 9 21 27 AM
Website is being server-side rendered, so initially, before first render window object isn't available, the plant creation is dependent on the locally stored-randomly generated number

to resolve the issue make sure that before rendering the plant object, the window object is available

`//wait till window object is available
  const [renderPlant, setPlant] = useState(null);
  useEffect(() => {
    const result = typeof window !== 'undefined';
    if (result) {
      setPlant(true);
    }
  }, []);
return renderPlant ? <Plant/> : null
`

**Comment by dhruv10** [comment]
@bhaskarSingh 
> Website is being server-side rendered, so initially, before first render window object isn't available, the plant creation is dependent on the locally stored-randomly generated number

> to resolve the issue make sure that before rendering the plant object, the window object is available

Resolved in 02a335f99489c2ff84ed167049c89172104dddc9

**Comment by bhaskarSingh** [comment]
@bhaskarSingh looks good
what should happen when zombies reach the plant? it kinda feels disconnected as nothing happens in this case

**Comment by bhaskarSingh** [comment]
closes #43

**Pull request merged**
