### PR TITLE
Game enhancements - UI and responsiveness

### LINKED ISSUE #66: Game implementation enhancement
1.  Updating Modal UI with respect to Figma design: [firgma](https://www.figma.com/file/hcoRbRF5fZREDTJkLl7cXk/BUIDL-for-Tezos?node-id=886%3A2)
2. making game mobile view responsive

### PR DESCRIPTION
**Pull request by dhruv10**
**What does this PR do?**
Fixes #66 

**Screenshots(optional)**

Implemented these modals on game over - both win and lose. Please check @AbhinavThukral97, the circle in behind animates.

image
image

### CODE REVIEW

**Comment by bhaskarSingh** [comment]
There is inconsistency in ball size across diff plant size
Screenshot 2020-04-23 at 6 33 31 PM

Screenshot 2020-04-23 at 6 36 26 PM

Screenshot 2020-04-23 at 6 35 31 PM

Screenshot 2020-04-23 at 6 34 52 PM
Screenshot 2020-04-23 at 6 35 26 PM

**Comment by bhaskarSingh** [comment]
> making game mobile view responsive

does the pr also resolve this issue?

**Comment by AbhinavThukral97** [comment]
Game Night Complete Loss
Modal for when the user loses the game.

I think the "You Lose" modal needs to be different. Sharing a design for reference.

**Comment by dhruv10** [comment]
> does the pr also resolve this issue?

Yes @bhaskarSingh

**Pull request merged**
